CREATE TABLE IF NOT EXISTS "example" (
    id UUID PRIMARY KEY NOT NULL DEFAULT uuid_generate_v1(),
    name VARCHAR(50),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN  DEFAULT false
);