CREATE TABLE IF NOT EXISTS ${table~} (
  id UUID PRIMARY KEY NOT NULL DEFAULT uuid_generate_v1(),
  user_id UUID NOT NULL,
  title VARCHAR(50) NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted BOOLEAN DEFAULT false,
  FOREIGN KEY (user_id) REFERENCES "user"(id)
)