CREATE TABLE IF NOT EXISTS "topic" (
  id UUID PRIMARY KEY NOT NULL DEFAULT uuid_generate_v1(),
  title VARCHAR(30) NOT NULL,
  is_private BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted BOOLEAN DEFAULT FALSE,
  UNIQUE(title)
)